apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: gravity-gha
spec:
  replicas: 3
  selector:
    matchLabels:
      name: gravity-gha
  template:
    metadata:
      labels:
        name: gravity-gha
    spec:
      containers:
      - name: gravity-gha
        image: 63038688/gravity-gha
        ports:
        - containerPort: 80
          name: http
