name: CD  # Nombre del workflow

on:  # Evento que activa el workflow
  push:
    branches:
      - master  # Se ejecuta en el push a la rama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # El trabajo se ejecuta en una máquina virtual Ubuntu

    steps:
    - name: Checkout code  # Paso para clonar el código del repositorio
      uses: actions/checkout@v3

    - name: Set up Docker Buildx  # Configuración de Docker Buildx para compilaciones multiplataforma
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Registry  # Inicia sesión en Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image  # Compila y sube la imagen de Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: your-docker-username/your-app:${{ github.sha }}  # Reemplaza con tu nombre de usuario y aplicación

    # Configuración de kubeconfig para conectarse al clúster de Kubernetes
    - name: Set up kubeconfig  
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
      env:  # Se asegura que la variable de entorno KUBECONFIG esté disponible
        KUBECONFIG: $HOME/.kube/config

    # Crear el namespace si no existe - Se corrigió la ubicación incorrecta del 'with'
    - name: Create namespace if not exists
      run: |
        kubectl get namespace prueba || kubectl create namespace prueba

    # Actualiza la imagen del despliegue en Kubernetes - Se movió 'with' bajo 'uses' correctamente
    - name: Update deployment image
      uses: steebchen/kubectl@v2.0.0  # Corrección: 'with' debe ir bajo 'uses' no 'run'
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n prueba set image --record deployment/gravity-gha gravity-gha=your-docker-username/your-app:${{ github.sha }}

    # Verificar el despliegue en Kubernetes
    - name: Verify deployment rollout
      uses: steebchen/kubectl@v2.0.0  # Corrección: 'with' debe ir bajo 'uses' no 'run'
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n prueba rollout status deployment/gravity-gha

    # Obtener los pods en el namespace para ver el estado
    - name: Get pods in namespace
      run: |
        kubectl get pods -n prueba
