name: CD  # Nombre del workflow

on:  # Evento que activa el workflow
  push:
    branches:
      - master  # Se ejecuta en el push a la rama master

jobs:
  docker:
    runs-on: self-hosted  # Runner auto-hospedado en macOS
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 63038688/prueba-gha:${{ github.sha }}

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: self-hosted  # Runner auto-hospedado en macOS
    needs: docker
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy to cluster with kubectl
        run: |
          kubectl set image --record deployment/prueba-gha prueba-gha=63038688/prueba-gha:${{ github.sha }} -n prueba
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/prueba-gha -n prueba
        env:
          KUBECONFIG: $HOME/.kube/config
