name: CD  # Nombre del workflow

on:  # Evento que activa el workflow
  push:
    branches:
      - master  # Se ejecuta en el push a la rama master

jobs:
  docker:
    runs-on: ubuntu-latest  # El trabajo se ejecuta en una máquina virtual Ubuntu

    steps:
      - name: Set up QEMU  # Configuración de QEMU para la emulación de arquitecturas
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx  # Configuración de Docker Buildx para compilaciones multiplataforma
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub  # Inicia sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push  # Compila y sube la imagen de Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 63038688/gravity-gha:${{ github.sha }}  # Etiqueta con el hash del commit

  deploy-to-cluster:
    name: Deploy to Cluster  # Despliegue al clúster de Kubernetes
    runs-on: ubuntu-latest
    needs: docker  # Necesita que el trabajo 'docker' se complete antes

    steps:
      # Configuración del kubeconfig para conectarse al clúster de Kubernetes
      - name: Set up kubeconfig  
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      # Crear el namespace si no existe - Usar 'env' para pasar el KUBECONFIG
      - name: Create namespace if not exists
        run: kubectl create namespace prueba || true
        env:
          KUBECONFIG: $HOME/.kube/config

      # Desplegar en el clúster de Kubernetes
      - name: Deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: -n prueba set image --record deployment/gravity-gha gravity-gha=63038688/gravity-gha:${{ github.sha }}

      # Verificar el estado del despliegue
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: -n prueba rollout status deployment/gravity-gha

      # Depuración y verificación de la conexión con el clúster
      - name: Debug cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -n prueba
        env:  # Se debe utilizar 'env' para pasar KUBECONFIG
          KUBECONFIG: $HOME/.kube/config
