name: CD  # Nombre del workflow

on:  # Evento que activa el workflow
  push:
    branches:
      - master  # Se ejecuta en el push a la rama master

jobs:
  deploy:
    name: Deploy to Cluster  # Despliegue al clúster de Kubernetes
    runs-on: ubuntu-latest

    steps:
      # Configuración del kubeconfig para conectarse al clúster de Kubernetes
      - name: Set up kubeconfig  
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      # Crear el namespace si no existe - Usar 'env' para pasar el KUBECONFIG
      - name: Create namespace if not exists
        run: kubectl create namespace prueba || true
        env:
          KUBECONFIG: $HOME/.kube/config

      # Desplegar en el clúster de Kubernetes
      - name: Deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: -n prueba set image --record deployment/gravity-gha gravity-gha=63038688/gravity-gha:${{ github.sha }}

      # Verificar el estado del despliegue
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: -n prueba rollout status deployment/gravity-ghahttps://github.com/killerbrokerchile/gravity-gha/actions/runs/10476023077

      # Depuración y verificación de la conexión con el clúster
      - name: Debug cluster connection
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -n prueba
        env:  # Se debe utilizar 'env' para pasar KUBECONFIG
          KUBECONFIG: $HOME/.kube/config
