name: CD  # Nombre del workflow

on:  # Evento que activa el workflow
  push:
    branches:
      - master  # Se ejecuta en el push a la rama master

jobs:
  deploy-to-cluster:
    name: deploy to cluster
    runs-on: self-hosted  # Se mantiene en el runner auto-hospedado macOS
    needs: docker
    steps:
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Deploy to cluster with kubectl
        run: |
          kubectl set image --record deployment/prueba-gha prueba-gha=63038688/prueba-gha:${{ github.sha }} -n prueba
        env:
          KUBECONFIG: $HOME/.kube/config

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/prueba-gha -n prueba
        env:
          KUBECONFIG: $HOME/.kube/config