on:
  push:
    branches:
      - master
name: CD

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: 63038688/gravity-gha:${{ github.sha }}

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Create namespace if not exists
      run: kubectl create namespace prueba || true
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n prueba set image --record deployment/gravity-gha gravity-gha=63038688/gravity-gha:${{ github.sha }}
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n prueba rollout status deployment/gravity-gha
    - name: Debug cluster connection
      run: |
        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -n prueba
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
